### PR TITLE
Allows filter command to filter for marked and unmarked commands

### LINKED ISSUE #137: Extend filter command to filter for marked contacts

### PR DESCRIPTION
**Pull request by imkwokyong**
Closes #137 

Add prefixes "m/" and "u/" for marked and unmarked contacts.
Filter command now supports two formats:
1. `filter FIELD_PREFIX_1 KEYWORD [MORE_KEYWORDS]`
2. `filter FIELD_PREFIX_2`

Where 
* FIELD_PREFIX_1: one of "n/", "p/", "e/", "c/", "j/", "t/"
* FIELD_PREFIX_2: one of "m/", "u/"

Edited typicalPersonsAddressBook.json in test/data to facilitate tests for marked and unmarked contacts.
Relevant tests added and passes all tests.
UG and DG updated (the relevant parts)

### CODE REVIEW

**Review by xavierpok — APPROVED** [review]
Small changes overall, LGTM.

One other thing from my quick UI testing (that shouldn't affect whether this is good to merge) that I discovered :

No indication that you gave it in a funny format. Carry-over behaviour from last iterations, and working as intended. (E.g. `filter m/ John Wick` doesn't tell you explicitly that `John Wick` was discarded)

Might consider implementing telling the user that extra args have been discarded if we're expecting the user to be rather misinput-prone

**Comment by imkwokyong** [comment]
Thank you for reviewing the PR.
Updated UG and test comments based on your suggestions.
The UI indication part can be done later as a separate PR, when we optimize the message for users.

**Comment by xavierpok** [comment]
> Thank you for reviewing the PR. Updated UG and test comments based on your suggestions. The UI indication part can be done later as a separate PR, when we optimize the message for users.

Thanks! LGTM still, just need a 2nd review

**Comment by Angelyxx** [comment]
LGTM!

**Pull request merged**
