### PR TITLE
Clarify that adding already-passed schedule is intended

### LINKED ISSUE #189: [PE-D][Tester A] Accepting dates that are before current time
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>

I do not think there is any reason why i would want to add a schedule meeting that has already passed.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Badatprogrammiing/ped#1

### PR DESCRIPTION
**Pull request by xavierpok**
Clarifies that behaviour is intentional and adds a suggested use case
I.e. this behaviour is neither a bug nor a feature flaw. (good!)

Closes #189

### CODE REVIEW

**Review by Angelyxx — DISMISSED** [review]
Pretty straightforward, LGTM!

**Review by imkwokyong — CHANGES_REQUESTED** [review]
LGTM but need to resolve merge conflicts before approval.

**Comment by xavierpok** [comment]
Merge conflicts resolved

**Review by imkwokyong — APPROVED** [review]
LGTM!

**Pull request merged**
