### PR TITLE
Fix index parsing to give correct error for too-big-integer & edit test cases

### LINKED ISSUE #210: [PE-D][Tester C] Unexpected error message when index value is higher than int
When typing in an invalid index, the expected behaviour is to get an invalid index error:

However, for large integer values, it gives a different error instead:

Users might be confused about what is wrong with their command. While it is unlikely for students to have more connections than can be stored in the int datatype, this may also point to an underlying bug when the database has that many connections, where users are unable to access the values past a certain index.

Some possible changes are to read the entire number or to add a note in the User Guide about the limit of connections possible in the application.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: rocketninja7/ped#5

### PR DESCRIPTION
**Pull request by xavierpok**
Closes #210 

Now, gives error to correctly reflect that the number is too big.

The if-else ladder should catch cases where it's negative and zero (as commented)

Throws the too-big message if and only if the number is larger than `Integer.MAX_VALUE`.

### CODE REVIEW

**Comment by xavierpok** [comment]
Note that this might be due for a refactor but that's a bit too big to really catch while doing bugfixes

**Review by imkwokyong — CHANGES_REQUESTED** [review]
Suggest to add a line in the User Guide to indicate the maximum number of contacts possible in the contact list, like what the corresponding issue mentioned

**Comment by xavierpok** [comment]
UG updated.

**Review by imkwokyong — APPROVED** [review]
LGTM!

**Pull request merged**
